export const APP = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_TOKEN: "SET_TOKEN",
};
export const ARTWORK = {
  SET: "SET_ARTWORK",
  SET_SELECTED_TEMPLATE: "SET_ARTWORK_SELECTED_TEMPLATE",
  SET_SELECTED_LAYERS: "SET_ARTWORK_SELECTED_LAYERS",
  SET_LAYERS: "SET_ARTWORK_LAYERS",
  SET_LAYER: "SET_ARTWORK_LAYER",
  SET_CLIPBOARD: "SET_ARTWORK_CLIPBOARD",
  SET_CTRL: "SET_ARTWORK_CTRL",
  SET_THUMBNAIL: "SET_ARTWORK_THUMBNAIL",
  ADD_LAYER: "ARTWORK_ADD_LAYER",
  UNDO: "ARTWORK_REDO",
  SET_PREVIEW: "ARTWORK_SET_PREVIEW",
};
export const MOCKUP = {
  SET: "SET_MOCKUP",
  SET_SELECTED_LAYERS: "SET_MOCKUP_SELECTED_LAYERS",
  SET_LAYERS: "SET_MOCKUP_LAYERS",
  SET_LAYER: "SET_MOCKUP_LAYER",
  SET_CTRL: "SET_MOCKUP_CTRL",
  SET_CLIPBOARD: "SET_MOCKUP_CLIPBOARD",
  SET_MOCKUPS: "SET_MOCKUPS_MANAGE",
};
export const CAMPAIGN = {
  SET: "SET_CAMPAIGN",
  SET_SELECTED_ARTWORK: "CAMPAIGN_SET_SELECTED_ARTWORK",
  SET_SETTINGS: "SET_CAMPAIGN_SETTINGS",
  RESET: "RESET_CAMPAIGN",
};
