version: "3.5"
services:
  personalized_web:
    image: nginx
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./out:/usr/share/nginx/html
      - ./nginx.log:/var/log/nginx/error.log
